### ISSUE TITLE
Review needed

### ISSUE THREAD

**Issue by bastienjacoud** [PolytechLyon/isi3-test-jacoud_remond_tp7#1]
Le TP sur les tests est terminé.

*Bastien*

**Comment by Slashgear** [comment]
Super usage fonctionnel https://github.com/PolytechLyon/isi3-test-jacoud_remond_tp7/blob/c91549aa5b545e86d22dd93e6ea2a941dfb99e9f/fizzbuzz/src/main/java/FizzBuzz.java#L50-L55

Sinon c'est nickel
